version: '3.1'

services:
    mongo:
        image: mongo
        ports:
            - 27017:27017

    notes-js:
        image: jgraham0/notes-js
        ports:
            - 8080:8080
        environment:
            DB_URL: mongodb://mongo:27017
        volumes:
            - ~/Documents/notes:/notes
